#!/usr/bin/env python3


import sys
import os
import re
import main
import gtypes


class clist(list):

    e_regex = "'([^']+)'"
    f_regex = "(\d+)?\.\d+"

    def __init__(self, cstring):
        elems = re.findall(clist.e_regex, cstring)
        items = re.sub(clist.e_regex, "", cstring).split(" ")
        list.__init__(self, self._read(items, elems))

    def _read(self, rems, reps):
        for val in rems:
            if not val:
                yield gtypes.GoghString(reps.pop(0))
            elif val.isnumeric():
                yield gtypes.GoghInteger(val)
            elif re.match(clist.f_regex, val):
                yield gtypes.GoghDecimal(val)
            else:
                yield gtypes.GoghString(val)


class GoghCLIHandler(object):

    # Storage

    _itypes = {
        "s": gtypes.GoghString,
        "i": gtypes.GoghInteger,
        "d": gtypes.GoghDecimal,
        "a": clist,
    }

    # Controllers

    def __init__(self, flags=None, code=None, ip=None, *args):
        self.flags = flags
        self.code = None
        self.ip = self._getiptype()(ip) if ip != None else None
        self.out = bool("o" in flags) if (flags != None) else False
        self.err = None if (flags != None) and (code != None) else [1]
        if (flags != None) and ("f" in flags) and (code != None):
            if os.path.isfile(code):
                with open(code, 'rb') as f:
                    self.code = f.read()
            else:
                self.err = [2, code]
        elif (code != None):
            self.code = code
        else:
            self.err = [1]

    def _getiptype(self):
        if self.flags:
            mtypes = sum(map(lambda i: i in GoghCLIHandler._itypes, self.flags))
            if 0 < mtypes < 2:
                find = GoghCLIHandler._itypes.get
                return [find(i) for i in self.flags if find(i)][0]
            else:
                self.err = [1]
        return gtypes.GoghString

    def run(self):
        end = "\n" if (not self.flags) or ("n" in self.flags) else ""
        return main.Gogh(self.code, self.ip, self.out, self.err, end)


instance = GoghCLIHandler(*sys.argv[1:]).run()
